#!/usr/bin/env python3
"""
build_fanart.py — collect fanart from Justin's fanart folder, optimize it,
and emit the carousel manifest.

  source : C:/Users/Justin/Pictures/0000000000000_JIAN_FANART (root + 1 level)
  output : assets/fanart/<slug>.webp   (max edge 1400, q82)
           data/fanart.js              (window.JIAN_FANART)

CREDITS COME FROM FILENAMES. Rename a source file and re-run to fix a credit.
Skips videos, PSDs, "- Copy" files and exact stem duplicates.
"""
import json
import os
import re

from PIL import Image

SRC = r"C:/Users/Justin/Pictures/0000000000000_JIAN_FANART"
ROOT = r"C:/Users/Justin/Desktop/neo-jian-site"
OUT = os.path.join(ROOT, "assets", "fanart")
DATA = os.path.join(ROOT, "data")

EXTS = (".png", ".jpg", ".jpeg", ".webp", ".gif")
Image.MAX_IMAGE_PIXELS = 80_000_000

# July 2026 review — suggestive (bikini/pinup/cleavage-heavy). Not explicit,
# but hidden when the visitor flips the SUGGESTIVE toggle off.
SUGGESTIVE_STEMS = {
    "vri0bn1m", "ectosnacks", "stronk", "longnaut", "orgn", "jaaaaaaaaaan_k1d",
    "skully-promo-final-02-1-2", "skully_valk_nowatermark", "mochiluce",
    "mayamayamaya", "mayamayamaya_ii", "stephzaps_art", "gdhbwewoaastuu",
    "gslv98dx0aartjo", "for_jian_sen", "gpwj_wexmaasqhd", "gooevznawaejbec",
    "sade_color", "djsaturn", "djsaturn2",
}

# July 2026 review — explicit (nudity/pasties/panty-flash) or duplicate variants.
# Source folder is NEVER modified; these are only skipped for the site.
SKIP_STEMS = {
    # explicit
    "capture", "8oa0fxoq.jpg large", "gs4qarmw0aa58yk", "jian_icon", "jian_icon_2",
    "jian_icon_3", "jian_icon_4", "jian_icon_5", "jian_icon_6", "gc3qkjhxuaa2s8m",
    "gyxoko8wcaathfs", "this_one_gal", "topburg", "boon02", "boon1", "boon2",
    "enuu", "newfa", "swee7nectar", "topp", "valentine_-_jian", "tofo", "freaky_aggie",
    # duplicate variants (one kept)
    "dztmkp4h", "fridgey1", "fridgey2", "jackson", "jacksonclr", "jacksonflx",
    "jian", "jian1", "secret_santa", "skully-promo-final-02-1-1",
    "skully-promo-final-02-1", "skully_valk", "toppppp", "jacksonfix",
    # reference photos / screenshots / non-art (per Justin, July 2026)
    "drawpega48", "finger-by-partykathat", "gwm1imobkaaep7s", "sketchy",
    "facebook", "facebook_002", "creep", "nokl", "noklji", "noklmonke", "jess",
}

# stems matched by prefix (case-insensitive) — phone photos, app screenshots,
# 3D viewport captures, hash-named references
SKIP_PREFIXES = (
    "img_", "screenshot", "rn_image_picker",
    "33c093ac8b683674c7a6571645ff0df3", "def74ef70a8177eda3066273ebc99",
    "8e967144ed6ba23b53ca8bf40cb5e0dc", "864763366014713856",
    "db796582a8787b97ae7b1a40012a0a",
)


def slugify(s):
    s = re.sub(r"[^A-Za-z0-9_-]+", "-", s).strip("-")
    return s[:60] or "piece"


def main():
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(DATA, exist_ok=True)
    items = []
    seen_stems = set()

    candidates = []
    for dirpath, dirnames, filenames in os.walk(SRC):
        depth = os.path.relpath(dirpath, SRC)
        if depth != "." and os.sep in depth:
            dirnames[:] = []  # one level only
            continue
        for fn in sorted(filenames):
            candidates.append((dirpath, fn, depth))

    for dirpath, fn, depth in candidates:
        stem, ext = os.path.splitext(fn)
        if ext.lower() not in EXTS:
            continue
        if stem.lower().endswith("- copy") or stem.lower().endswith(" copy"):
            continue
        key = stem.lower()
        if key in seen_stems or key in SKIP_STEMS or key.startswith(SKIP_PREFIXES):
            continue
        seen_stems.add(key)

        src = os.path.join(dirpath, fn)
        slug = slugify(stem)
        out_name = f"{slug}.webp"
        out_path = os.path.join(OUT, out_name)
        try:
            with Image.open(src) as im:
                im = im.convert("RGB")
                if max(im.size) > 1400:
                    im.thumbnail((1400, 1400), Image.LANCZOS)
                im.save(out_path, "WEBP", quality=82, method=6)
        except Exception as e:  # noqa: BLE001
            print(f"  !! {fn}: {e}")
            continue
        items.append({"img": f"assets/fanart/{out_name}", "by": stem,
                      "sug": 1 if stem.lower() in SUGGESTIVE_STEMS else 0})

    with open(os.path.join(DATA, "fanart.js"), "w", encoding="utf-8") as f:
        f.write("// generated by tools/build_fanart.py — credits come from source filenames\n")
        f.write("window.JIAN_FANART = ")
        f.write(json.dumps(items, ensure_ascii=False, separators=(",", ":")))
        f.write(";\n")
    print(f"fanart: {len(items)} pieces -> data/fanart.js")


if __name__ == "__main__":
    main()
