#!/usr/bin/env python3
"""
sync_fanart_review.py — the fanart reel's curator.

The FANART REVIEW folder on the Desktop IS the source of truth now
(this supersedes build_fanart.py, which scanned the raw Pictures folder):

  <root>/<slug>.webp            -> reel piece, credit = filename
  <root>/<artist>/<file>.webp   -> reel piece, credit = the folder name
  *_suggestive.webp             -> hidden when the SUGGESTIVE toggle is off
                                   (suffix is stripped, not part of output)

Deletes = removals. Renames = credit changes. Then run this and push.

  output : assets/fanart/<slug>.webp        (copied, already optimized)
           assets/fanart/thumbs/<slug>.webp (280px, q70 — carousel)
           data/fanart.js                   (window.JIAN_FANART)
"""
import json
import os
import shutil

from PIL import Image

REVIEW = r"C:/Users/Justin/Desktop/FANART REVIEW"
ROOT = r"C:/Users/Justin/Desktop/neo-jian-site"
OUT = os.path.join(ROOT, "assets", "fanart")
THUMBS = os.path.join(OUT, "thumbs")
DATA = os.path.join(ROOT, "data")
THUMB_EDGE = 280

# legacy suggestive list from build_fanart.py — keep these flagged even
# though the review files carry no _suggestive suffix
SUGGESTIVE_STEMS = {
    "vri0bn1m", "ectosnacks", "stronk", "longnaut", "orgn", "jaaaaaaaaaan_k1d",
    "skully-promo-final-02-1-2", "skully_valk_nowatermark", "mochiluce",
    "mayamayamaya", "mayamayamaya_ii", "stephzaps_art", "gdhbwewoaastuu",
    "gslv98dx0aartjo", "for_jian_sen", "gpwj_wexmaasqhd", "gooevznawaejbec",
    "sade_color", "djsaturn", "djsaturn2",
}


def main():
    # gather entries: (slug_base, credit, sug, src)
    entries = []
    for f in sorted(os.listdir(REVIEW)):
        p = os.path.join(REVIEW, f)
        if os.path.isfile(p) and f.lower().endswith(".webp"):
            stem = f[:-5]
            sug = 1 if stem.endswith("_suggestive") else 0
            if sug:
                stem = stem[: -len("_suggestive")]
            entries.append([stem, stem, sug, p])
    for artist in sorted(os.listdir(REVIEW)):
        d = os.path.join(REVIEW, artist)
        if not os.path.isdir(d):
            continue
        for f in sorted(os.listdir(d)):
            p = os.path.join(d, f)
            if os.path.isfile(p) and f.lower().endswith(".webp"):
                stem = f[:-5]
                sug = 1 if stem.endswith("_suggestive") else 0
                if sug:
                    stem = stem[: -len("_suggestive")]
                entries.append([stem, artist, sug, p])

    # slugs must be unique — prefix with the credit on collision
    seen = {}
    for e in entries:
        stem = e[0]
        if stem in seen:
            seen[stem] += 1
            e[0] = f"{e[1]}-{stem}"
        else:
            seen[stem] = 1
    dupes = [s for s, c in seen.items() if c > 1]
    if dupes:
        print(f"  .. collisions prefixed: {dupes}")

    # wipe + rebuild outputs
    os.makedirs(OUT, exist_ok=True)
    os.makedirs(THUMBS, exist_ok=True)
    for d in (OUT, THUMBS):
        for f in os.listdir(d):
            if f.lower().endswith(".webp"):
                os.remove(os.path.join(d, f))

    items = []
    for slug, credit, sug, src in entries:
        out_name = f"{slug}.webp"
        shutil.copyfile(src, os.path.join(OUT, out_name))
        with Image.open(src) as im:
            im = im.convert("RGB")
            if max(im.size) > THUMB_EDGE:
                im.thumbnail((THUMB_EDGE, THUMB_EDGE), Image.LANCZOS)
            im.save(os.path.join(THUMBS, out_name), "WEBP", quality=70, method=6)
            tw, th = im.size
        if slug.lower() in SUGGESTIVE_STEMS:
            sug = 1
        items.append({"img": f"assets/fanart/{out_name}",
                      "thumb": f"assets/fanart/thumbs/{out_name}",
                      "w": tw, "h": th, "by": credit, "sug": sug})

    with open(os.path.join(DATA, "fanart.js"), "w", encoding="utf-8") as f:
        f.write("// generated by tools/sync_fanart_review.py — the Desktop FANART REVIEW folder is the source of truth\n")
        f.write("window.JIAN_FANART = ")
        f.write(json.dumps(items, ensure_ascii=False, separators=(",", ":")))
        f.write(";\n")
    print(f"fanart: {len(items)} pieces ({sum(i['sug'] for i in items)} suggestive) -> data/fanart.js")


if __name__ == "__main__":
    main()
