#!/usr/bin/env python3
"""
update_x.py — refresh the "latest X post" card data.

Fetches the public syndication timeline for @jiansketch (no API key needed),
finds the most recent post, and writes:
  data/xpost.js          window.JIAN_XPOST = {text, date, link, media, avatar}
  assets/img/x_avatar.jpg  (profile avatar, refreshed if changed)

Run it any time:  python tools/update_x.py
Also runs daily via .github/workflows/update-x.yml.
"""
import json
import os
import re
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
USER = "jiansketch"
TIMELINE = f"https://syndication.twitter.com/srv/timeline-profile/screen-name/{USER}?dnt=true"

TWEET_RE = re.compile(
    r'"created_at":"(?P<date>[^"]+)".*?"full_text":"(?P<text>(?:\\.|[^"\\])*)","id_str":"(?P<id>\d+)"',
    re.S,
)
MEDIA_RE = re.compile(r'"media_url_https":"(?P<u>(?:\\.|[^"\\])*)"')
AVATAR_RE = re.compile(r'"profile_image_url_https":"(?P<u>(?:\\.|[^"\\])*)"')


def fetch(url, tries=4):
    import time
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36",
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
    }
    for k in range(tries):
        try:
            req = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(req, timeout=30) as r:
                return r.read()
        except urllib.error.HTTPError as e:
            if e.code == 429 and k < tries - 1:
                time.sleep(6 * (k + 1) ** 2)  # 6s, 24s, 54s
                continue
            raise


def unescape(s):
    return s.encode().decode("unicode_escape")


def main():
    import sys
    if "--from-file" in sys.argv:
        blob = open(sys.argv[sys.argv.index("--from-file") + 1], encoding="utf-8", errors="replace").read()
    else:
        try:
            blob = fetch(TIMELINE).decode("utf-8", errors="replace")
        except (urllib.error.HTTPError, urllib.error.URLError) as e:
            # X rate-limits GitHub's runner IPs some days (daily 429s since
            # Aug 1 2026). If the card already has data, keep the last known
            # post and exit green — a stale card beats a failed workflow.
            if os.path.exists(os.path.join(ROOT, "data", "xpost.js")):
                print(f"timeline fetch blocked ({e}); keeping existing data/xpost.js")
                return
            raise

    # only tweets whose permalink belongs to the account (skips retweets/others)
    my_ids = set(re.findall(rf'"permalink":"/{USER}/status/(\d+)"', blob))
    tweets = []
    for m in TWEET_RE.finditer(blob):
        tid = m.group("id")
        if tid not in my_ids:
            continue
        date = m.group("date")
        text = unescape(m.group("text"))
        tweets.append((date, text, tid, m.start()))

    if not tweets:
        raise SystemExit("no tweets parsed — syndication format changed?")

    from email.utils import parsedate_to_datetime
    tweets.sort(key=lambda t: parsedate_to_datetime(t[0]), reverse=True)
    date, text, tid, pos = tweets[0]

    # media lives in this tweet's own entities block (between created_at and full_text)
    media = ""
    for mm in MEDIA_RE.finditer(blob, tweets[0][3], tweets[0][3] + 20000):
        media = unescape(mm.group("u"))
        break
    if media:
        media = re.sub(r"\\/", "/", media) + "?name=small"

    avatar_url = ""
    am = AVATAR_RE.search(blob)
    if am:
        avatar_url = unescape(am.group("u")).replace("\\/", "/").replace("_normal", "_200x200")

    avatar_rel = ""
    if avatar_url:
        ext = ".jpg"
        avatar_path = os.path.join(ROOT, "assets", "img", "x_avatar" + ext)
        try:
            data = fetch(avatar_url)
            if not os.path.exists(avatar_path) or open(avatar_path, "rb").read() != data:
                open(avatar_path, "wb").write(data)
            avatar_rel = "assets/img/x_avatar" + ext
        except Exception as e:  # noqa: BLE001
            print("  avatar fetch failed:", e)

    # strip trailing t.co media link from text (it's the image itself)
    text = re.sub(r"\s*https://t\.co/\S+\s*$", "", text).strip()

    out = {
        "text": text,
        "date": parsedate_to_datetime(date).strftime("%Y-%m-%d"),
        "link": f"https://x.com/{USER}/status/{tid}",
        "media": media,
        "avatar": avatar_rel,
        "user": USER,
    }
    os.makedirs(os.path.join(ROOT, "data"), exist_ok=True)
    with open(os.path.join(ROOT, "data", "xpost.js"), "w", encoding="utf-8") as f:
        f.write("// generated by tools/update_x.py — do not hand-edit\n")
        f.write("window.JIAN_XPOST = ")
        f.write(json.dumps(out, ensure_ascii=False, indent=2))
        f.write(";\n")
    print(f"latest post {tid} ({date}): {text[:60]!r} media={'yes' if media else 'no'}")


if __name__ == "__main__":
    main()
